import { FlatCompat } from "@eslint/eslintrc";

// ESLint 9 reads flat config only, and eslint-config-next 15 still ships the
// legacy (eslintrc) shape, so its presets are translated here. `next lint`
// is not used: with no config it drops into an interactive prompt and exits
// 1, which is why the lint script had never actually run.
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  {
    ignores: [
      ".next/**",
      ".open-next/**",
      ".wrangler/**",
      "node_modules/**",
      // Python, not ours to lint here.
      "scripts/crawl4ai/**",
      // Generated by `wrangler types` and `next dev`.
      "cloudflare-env.d.ts",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
