"""Emit supabase/seed-events.sql: the bundled dataset as approved rows, so a
freshly connected database shows the same events the bundle does."""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = "/Users/brimay/Documents/Bri May/Github Bri/downtown-ps-events"

def q(v):
    if v is None: return "null"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def arr(xs):
    xs = [x for x in (xs or []) if x]
    return "array[" + ",".join(q(x) for x in xs) + "]::text[]" if xs else "'{}'::text[]"

def slug(s): return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")[:70]

events = json.load(open(os.path.join(REPO, "src/lib/events.generated.json")))
sources = json.load(open(os.path.join(REPO, "src/lib/sources.generated.json")))

out = []
A = out.append
A("-- ============================================================================")
A("-- Generated by scripts/crawl4ai/seed_sql.py from the bundled crawl dataset.")
A("-- Run after schema.sql + seed.sql. Idempotent: rows key on slug / dedupe_hash.")
A("-- ============================================================================")
A("")
# These rows are provenance for the crawled events, not targets for the
# scheduled scraper: its adapter registry (src/lib/scrapers/index.ts) doesn't
# know these keys, so they ship disabled to keep every run from logging
# 33 "no scraper registered" errors. The seven live sources from seed.sql are
# untouched and keep running.
A("insert into sources (slug, name, url, website, scraper_key, strategy, enabled, notes) values")
rows = []
for s in sources:
    note = f"One-shot Crawl4AI sweep, {s['notes']} Disabled: no scheduled adapter."
    rows.append(f"  ({q(s['slug'])}, {q(s['name'])}, {q(s['url'])}, {q(s['website'])}, "
                f"{q('crawl4ai:' + s['scraper_key'])}, {q(s['strategy'])}, false, {q(note)})")
A(",\n".join(rows))
A("on conflict (slug) do update set name = excluded.name, url = excluded.url,")
A("  website = excluded.website, notes = excluded.notes, enabled = excluded.enabled;")
A("")
A("insert into events (title, slug, description, start_at, end_at, venue, address, category,")
A("  tags, price, is_free, is_family_friendly, image_url, ticket_url, source_id, source_url,")
A("  status, origin, dedupe_hash) values")
rows = []
by_name = {s["name"]: s["slug"] for s in sources}
for e in events:
    src_slug = by_name.get(e.get("source_name"))
    src_expr = f"(select id from sources where slug = {q(src_slug)})" if src_slug else "null"
    rows.append(
        f"  ({q(e['title'])}, {q(e['slug'])}, {q(e['description'])}, {q(e['start_at'])}, "
        f"{q(e['end_at'])}, {q(e['venue'])}, {q(e['address'])}, {q(e['category'])}, "
        f"{arr(e.get('tags'))}, {q(e['price'])}, {q(bool(e['is_free']))}, "
        f"{q(bool(e['is_family_friendly']))}, {q(e['image_url'])}, {q(e['ticket_url'])}, "
        f"{src_expr}, {q(e['source_url'])}, 'approved', 'scraper', {q(e['id'])})")
A(",\n".join(rows))
A("on conflict (slug) do update set")
A("  description = excluded.description, start_at = excluded.start_at, end_at = excluded.end_at,")
A("  venue = excluded.venue, address = excluded.address, category = excluded.category,")
A("  tags = excluded.tags, price = excluded.price, is_free = excluded.is_free,")
A("  is_family_friendly = excluded.is_family_friendly, image_url = excluded.image_url,")
A("  ticket_url = excluded.ticket_url, source_url = excluded.source_url, updated_at = now();")
A("")

path = os.path.join(REPO, "supabase", "seed-events.sql")
open(path, "w").write("\n".join(out))
print("wrote", path, f"({len(events)} events, {len(sources)} sources, {os.path.getsize(path)//1024} KB)")
