/**
 * Builds the chat's knowledge base.
 *
 *   npm run knowledge
 *
 * Two steps:
 *
 *   1. Render the crawl archive (data/pleasanton-events.json) into markdown
 *      digests, one file per source, under knowledge/events/. These are
 *      generated files: edit the crawl, not the digests.
 *
 *   2. Compile every markdown file under knowledge/ (digests and any raw
 *      crawled pages under knowledge/pages/) into src/lib/knowledge.generated.json,
 *      the chunk index the /api/chat search tool reads.
 *
 * Pass --index-only to skip step 1, e.g. after hand-adding pages.
 */
import fs from "node:fs";
import path from "node:path";
import { eventToMarkdown } from "../src/lib/knowledge/render";
import { parseMarkdownDocument } from "../src/lib/knowledge/parse";
import type { KnowledgeChunk, KnowledgeIndex } from "../src/lib/knowledge/types";

const ROOT = path.resolve(__dirname, "..");
const ARCHIVE = path.join(ROOT, "data", "pleasanton-events.json");
const KNOWLEDGE = path.join(ROOT, "knowledge");
const EVENTS_DIR = path.join(KNOWLEDGE, "events");
const OUT = path.join(ROOT, "src", "lib", "knowledge.generated.json");

interface ArchiveEvent {
  id: string;
  title: string;
  description: string | null;
  start_at: string;
  end_at: string | null;
  all_day: boolean;
  venue: string | null;
  address: string | null;
  city: string | null;
  region: string;
  category: string;
  tags: string[];
  price: string | null;
  is_free: boolean;
  is_family_friendly: boolean;
  ticket_url: string | null;
  source_name: string;
  source_url: string | null;
}

interface Archive {
  generated_at: string;
  window: { start: string; end: string };
  sources: { name: string; sample_url: string }[];
  events: ArchiveEvent[];
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

// Mirrors emit.py so a digest carries the same address and slug the site does.
function toEventLike(e: ArchiveEvent) {
  const city = e.city || (e.region === "Pleasanton" ? "Pleasanton" : null);
  let address = e.address;
  if (address && city && !address.toLowerCase().includes(city.toLowerCase())) {
    address = `${address}, ${city}, CA`;
  } else if (!address && city) {
    address = `${city}, CA`;
  }
  const tags = [...new Set([...(e.tags ?? []), e.region.toLowerCase().replace(/\s+/g, "-")])];
  return {
    id: e.id,
    title: e.title,
    slug: `${slugify(e.title)}-${e.id.slice(0, 6)}`,
    description: e.description,
    start_at: e.start_at,
    end_at: e.end_at,
    all_day: e.all_day,
    venue: e.venue,
    address,
    category: e.category,
    tags,
    price: e.price,
    is_free: e.is_free,
    is_family_friendly: e.is_family_friendly,
    ticket_url: e.ticket_url,
    source_url: e.source_url,
    source_name: e.source_name,
  };
}

function writeDigests(): void {
  const archive = JSON.parse(fs.readFileSync(ARCHIVE, "utf8")) as Archive;
  const bySource = new Map<string, ArchiveEvent[]>();
  for (const e of archive.events) {
    if (!bySource.has(e.source_name)) bySource.set(e.source_name, []);
    bySource.get(e.source_name)!.push(e);
  }
  const listingUrl = new Map(archive.sources.map((s) => [s.name, s.sample_url]));

  fs.mkdirSync(EVENTS_DIR, { recursive: true });
  for (const stale of fs.readdirSync(EVENTS_DIR)) {
    if (stale.endsWith(".md")) fs.unlinkSync(path.join(EVENTS_DIR, stale));
  }

  for (const [source, events] of bySource) {
    events.sort((a, b) => a.start_at.localeCompare(b.start_at));
    const header = [
      "---",
      `kind: events`,
      `source: ${source}`,
      `url: ${listingUrl.get(source) ?? ""}`,
      `crawled: ${archive.generated_at}`,
      `window: ${archive.window.start} to ${archive.window.end}`,
      `events: ${events.length}`,
      "---",
      "",
      `# ${source}`,
      "",
      `${events.length} events crawled from ${source} on ${archive.generated_at.slice(0, 10)}.`,
      "Generated by scripts/build-knowledge.ts from data/pleasanton-events.json. Do not edit by hand.",
      "",
    ];
    const body = events.map((e) => eventToMarkdown(toEventLike(e))).join("\n\n");
    const file = path.join(EVENTS_DIR, `${slugify(source)}.md`);
    fs.writeFileSync(file, `${header.join("\n")}\n${body}\n`);
    console.log(`wrote ${path.relative(ROOT, file)} (${events.length} events)`);
  }
}

function* walk(dir: string): Generator<string> {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.name.endsWith(".md")) yield full;
  }
}

function compileIndex(): void {
  const chunks: KnowledgeChunk[] = [];
  let documents = 0;
  for (const file of walk(KNOWLEDGE)) {
    const rel = path.relative(KNOWLEDGE, file).split(path.sep).join("/");
    if (rel === "README.md") continue;
    const parsed = parseMarkdownDocument(rel, fs.readFileSync(file, "utf8"));
    if (parsed.length === 0) continue;
    documents += 1;
    chunks.push(...parsed);
  }
  // Deterministic order keeps the generated file's diffs readable.
  chunks.sort((a, b) =>
    (a.date ?? "9999").localeCompare(b.date ?? "9999") || a.id.localeCompare(b.id),
  );
  const index: KnowledgeIndex = {
    generated_at: new Date().toISOString().slice(0, 19),
    documents,
    chunks,
  };
  fs.writeFileSync(OUT, JSON.stringify(index));
  const events = chunks.filter((c) => c.kind === "event").length;
  console.log(
    `wrote ${path.relative(ROOT, OUT)}: ${chunks.length} chunks (${events} events, ${chunks.length - events} page slices) from ${documents} documents, ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`,
  );
}

if (!process.argv.includes("--index-only")) writeDigests();
compileIndex();
